site_name: banbaibanzi
nav:
  - 主页:
      - 简介: index.md
  - 工具:
      - 插件:
          - chrome: tools/chrome.md
      - windows软件: tools/window.md
      - windows系统: tools/window-system.md
      - R星: tools/Rxing.md
  - 前端:
      - Vue:
          - Vue: vue/index.md
      - 工具:
          - vue常用库: web/vue-ku.md
          - nvm: web/nvm.md
          - ssh配置、vscode、扩展: web/ssh.md
          - oss视频首帧、在线二维码: web/oss.md
      - 知识点:
          - 防抖节流: web/debounce.md
          - sort打乱数组: web/sort.md
      - js:
          - ES6: web/es6.md
          - 判断属性是否存在、遍历数组: web/js-1.md
          - 变量提升: web/variate.md
      - css:
          - mixin、extend: web/css-1.md
          - css绘制: web/css-2.md
  - 有趣的网站: websites/index.md
  - mkdocs搭建:
      - mkdocs: mkdocs/index.md
theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: light
      toggle:
        icon: material/brightness-7
        name: light
      primary: blue grey
      accent: orange
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: dark
      primary: blue grey
      accent: orange
  font:
    text: Roboto Mono
  language: zh
  icon:
    logo: material/library
  # logo: assets/logo.jpg
  features:
    - navigation.tabs #tabs
    # - navigation.tabs.sticky  #tabs固定
    - navigation.sections
    - navigation.expand #打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.code.copy #复制代码块
    - search.suggest #搜索输入一些字母时推荐补全整个单词
extra_css:
  - stylesheets/Aplayer.min.css
  - stylesheets/extra.css
extra_javascript:
  - javascripts/Aplayer.min.js
  - javascripts/Meting.mim.js
  - javascripts/extra.js
extra:
  generator: false #删除页脚显示
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/banbaibanzi
