site_name: banbaibanzi
nav:
  - 主页:
      - aa: index.md
  - mkdocs搭建:
      - mkdocs: mkdocs/index.md
  - 测试页: home/index.md
theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/brightness-7
        name: light
      primary: blue grey
      accent: orange
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: dark
      primary: blue grey
      accent: orange
  font:
    text: Roboto Mono
  language: zh
  icon:
    logo: material/library
  # logo: assets/logo.jpg
  features:
    - navigation.tabs #tabs
    # - navigation.tabs.sticky  #tabs固定
    - navigation.sections
    - navigation.expand
    - content.code.copy #复制代码块
extra_css:
  - stylesheets/Aplayer.min.css
  - stylesheets/extra.css
extra_javascript:
  - javascripts/Aplayer.min.js
  - javascripts/Meting.mim.js
  - javascripts/extra.js
extra:
  generator: false #删除页脚显示
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/banbaibanzi
